<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-01T15:28:54</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e96625aa-5cc0-4471-ae60-ab36d7901bea</testSuiteGuid>
   <testCaseLink>
      <guid>b327639e-4c6a-4aa5-a752-254170a7c304</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Create Issue Test/User should be able to create issue successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85a603bc-fc08-4ed2-bcb5-3c52d620cff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec627c4c-6549-4a01-b9e2-605be351dd4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bba64aa6-0c6f-48f6-9c70-e9b5c15d2110</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3420820c-45c5-4cf3-a50f-05ec17025041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cba50a02-866d-4cec-8ae2-76f54a55bb74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d59c4a48-afb8-4b0b-9935-11480dc3308c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Create Issue Test/User should be able to create issue successfully - Copy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>069d7e85-e542-4883-8b95-d670611460b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acc2b70d-ec6d-446f-bde6-2af85236c519</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03d8b678-3744-48fe-b84f-ac3b7e3ce82b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7025da6b-46e1-43ca-bff1-75fb933b89a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25c3b66d-019e-405c-bacd-a142fe2c28ed</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
