<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c104d40b-6f5c-473e-b3c7-e680da52f0b3</testSuiteGuid>
   <testCaseLink>
      <guid>b0ed304a-4aec-41e7-8b9a-c1bb1e2908b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple examples/Verify an issue information</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f16fa85d-4dce-4485-ae78-47b941a7a91a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance examples/EXECUTABLE/api-2-issue-tests/Scenario - Create ticket successfully with API</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b1d3731-082d-4581-96f9-f8096f7053aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9377ed8-29a0-4962-a3c5-7fb6a437265f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>035beca4-79a5-4a4e-a7d0-9a15eb2216d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61abdf8c-30b0-410d-92d6-6c715fad9afd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2619d56d-67a6-4d53-8b49-36e5e6e72947</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9587783e-044f-44e1-a291-428d90015afb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance examples/EXECUTABLE/api-2-issue-tests/Scenario - Get issue information successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9df3ea07-7015-4f60-a53e-e78509f348fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d036061d-bb5c-4151-a56e-34ab51c5660b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f6eb841-ccb3-4e0d-8cd6-01405f134c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>835dfc40-853c-45c8-b2b4-c5d1020c54a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc9884df-ac77-4823-993f-a07fa50e4e02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87182904-55bf-43a6-aee0-617ff5749c32</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
